### ISSUE TITLE
Ambergris proper category type?

### ISSUE THREAD

**Issue by mrhoribu** [elanthia-online/scripts#106]
The following two items are only classified as "furrier" but not anything else so they are not picked up as loot when found. Not sure what they should be picked up as. Skin?

lump of black ambergris
lump of grey ambergris

**Comment by mrhoribu** [comment]
Only sellable to the furrier or alchemist.

**Comment by sandersch** [comment]
Does the alchemist or furrier pay more? I think these would make sense as a `reagent` since I know the grey form is used for making dye.

**Comment by mrhoribu** [comment]
So got my hands on a lump of grey ambergris and was able to determine the following sale price from various town merchants.

Furrier: 264
Gemshop: n/a
Alchemist: n/a
Pawnshop: 78

So based on that, I say we go ahead and leave it as furrier and just add both to the skin category as that seems to be where it can be sold for the most. Going to start the migration file now.

**Comment by mrhoribu** [comment]
closed as PR #108 resolved issue
