### ISSUE TITLE
Eherbs set herbsack command is broken[script] 

### ISSUE THREAD

**Issue by JaredDiCioccio** [elanthia-online/scripts#1069]
### Script Name

eherbs.lic

### Bug Report

When runnng `eherbs set herbsack <your herbsack>`  the herbsack does not get set because of the parameters passed to the Utility.settings_herbsack function. 

I'm not sure if setting herbsack from the gui works. It doesn't appear to. 

### Expected Behavior

My herbsack should get set. 

### Current Behavior

The Utility.settings_herbsack function exits prematurely at https://github.com/elanthia-online/scripts/blob/master/scripts/eherbs.lic#L2298

### Possible Solution

https://github.com/elanthia-online/scripts/blob/master/scripts/eherbs.lic#L2500

The CLI is passing `Script.current.vars[0]`, which is a string. So `return unless vars[2] == 'herbsack'` will of course return because it's just checking vars[2] which is a string, so it'll always just be the letter t. 

### Possible Solution

Should just pass Script.current.vars to the function.

**Comment by Deysh** [comment]
Thanks for the fix on the CLI. It should work on the next release. 

As for the noun issue, if you have multiple containers with the same noun you'll need to be more descriptive in the herbsack setting. You just need to enclose it with parenthesis - ;eherbs set herbsack "blue sack"
