### ISSUE TITLE
Eherbs does not work if your herbsack noun is the same as another container in your inventory and it appears first in your inventory[script] 

### ISSUE THREAD

**Issue by JaredDiCioccio** [elanthia-online/scripts#1074]
### Script Name

eherbs.lic

### Bug Report

Assuming you work around #1069 , Eherbs still breaks after successfully saving your herbsack. 

If you have another container on you with the same noun as your herbsack, Eherbs will not successfully find and set your herbsack when it tries to use herbs. 

This behavior is entirely dependent on the order your inventory is sorted in. 

These are the containers on my belt:

**`a punched suede sack drawn by feathered ties, a studded black suede belt pouch with a silver-edged flap, an indigo elesine sack embroidered with coils of shadowy eels,`**

The suede sack is my survival kit, the elesine sack is just a container.  In this configuration, Eherbs.lic will find my suede sack successfully when calling Utility.find_herbsack. 

However if the elesine sack appears first, Utility.find_herbsack will find it first and use it as the herbsack. It will then think you have no herbs. This breaks basically all expected behavior of Eherbs. 

### Expected Behavior

I expect to run ;eherbs and have it find my survival kit and then use doses from it to heal me. 

Also, ;eherbs stock breaks too since it keeps buying herbs and then stowing them in your herb stow, but then never seeing that you have anything in your herb stow.

### Current Behavior

It looks in the wrong container so thinks you have no herbs. 

### Possible Solution

The Utility.find_herbsack function is broken. 

This code block is used to find the GameObject for your herb container. 

   ```
   unless (
        herbsack = (
          GameObj.inv.find { |obj| obj.noun == EHerbs.data[:herb_container] } || 
          GameObj.inv.find { |obj| obj.name == EHerbs.data[:herb_container] } || 
          GameObj.inv.find { |obj| obj.name =~ /\b#{Regexp.escape(EHerbs.data[:herb_container])}$/i } || 
          GameObj.inv.find { |obj| obj.name =~ /\b#{EHerbs.data[:herb_container].split(' ').collect { |n| Regexp.escape(n) }.join(".*\\b")}/i }
        )
      )
```

In the broken scenario here, my herb_container is set to `punched suede sack`. However since i have an `elesine sack` sorted before my `punched suede sack` on my belt, this block finds the elesine sack first. 

It then thinks my elesine sack is my herbsack. Since it is not, Eherbs finds no herbs in it and will always go to buy new herbs regardless if your actual herbsack is full. 

I'm not 100% sure GameObj.find guarantees any sort order. So the order in your inventory may not matter. It appears to but I don't know how GameObj.find works under the hood enough. Order may not be guaranteed. 

Either way find_herbsack needs to be more robust.

**Comment by Deysh** [comment]
Thanks for the catch. It does seem to be a bit overkill. I'll change that so it doesn't grab the noun first.

**Comment by gs4-Xanlin** [comment]
why not just add the adjective to your herbsack so it doesn't match just a noun?

**Comment by JaredDiCioccio** [comment]
That doesn't work. I tried the full name of the survival kit, suede sack, punched suede sack, etc... As long as there's another "sack" of any kind on you eherbs might pick that up instead.

**Comment by Deysh** [comment]
this works for me...

;eherbs set herbsack "dirt-covered sack"
--- Lich: eherbs active.
eherbs setting saved: herbsack is now dirt-covered sack. (previous value: 'large sack')
--- Lich: eherbs has exited.
>;eherbs test
--- Lich: eherbs active.
[eherbs: dirt-covered sack]
--- Lich: eherbs has exited.
>;eherbs set herbsack "large sack"
--- Lich: eherbs active.
eherbs setting saved: herbsack is now large sack. (previous value: 'dirt-covered sack')
--- Lich: eherbs has exited.
>;eherbs test
--- Lich: eherbs active.
[eherbs: large sack]
--- Lich: eherbs has exited.

**Comment by Deysh** [comment]
also please make sure you are using the current version as it's been changing pretty frequently. 
Today (March 3, 2023) it is 1.5.8

**Comment by JaredDiCioccio** [comment]
Thanks @mrhoribu . That last pull request seems to have fixed the issue.
