### ISSUE TITLE
[rfc] echild needs better logic for determining dropoff location

### ISSUE THREAD

**Issue by JaredDiCioccio** [elanthia-online/scripts#1113]
### Script Name

echild

### RFC

I want echild to more intelligently parse the dropoff destination for lost children.

### Context

Not much context. Was running bounties with ebounty, and after rescuing a child echild.lic kicked in and brought us to the wrong town. I was mildly annoyed, the child was traumatized. 

### Examples

I just had a child rescue bounty starting out of Wehnimer's Landing. The child somehow got lost in Castle Varunar.... (seriously wtf are these kids doing in these places???). After killing the mean Phantasma that kidnapped the kid, echild started the return process. However it determined that the dropoff spot was in Vornavis. This is because it uses ;go2 to find the nearest guard. 

```
#------------------------------------------------------------------------------#
  # dropoff_points
  #------------------------------------------------------------------------------#
  dropoff_points = advguard = advguard2 = [];

  advguard = Map.current.find_all_nearest_by_tag("advguard");
  advguard2 = Map.current.find_all_nearest_by_tag("advguard2");
  dropoff_points = advguard | advguard2 | [2777, 2778, 2782, 2779, 2780, 2781, 2783, 2784, 2785, 2786, 2787];
```

Unfortunately, for me and this poor kid, that was outside Vornavis. 

```
>;go2 advguard
--- Lich: go2 active.
[go2: input: advguard]
ETA: 0:00:22.  111 rooms between this room (13983) and:
#5576 (u2130208):
[Vornavis, North Gate] (the holdings of Vornavis)
The sounds of the beast pens and other caravan noises to the north echo off the immense blue granite walls that surround Vornavis.  From within the walls come the familiar noises of city life that, in turn, combine with the animal noises to make an odd mix of sounds.  A guard stands at the gate into the city, watching carefully all who enter.
Obvious paths: north
```

Ebounty should have somehow recognized that I needed to return to the Landing. MAybe checking the bounty command output would work?

```
>bounty
Izaneth, your Adventurer's Guild information is as follows:
You currently have 48,011 unspent bounty points.
You have accumulated a total of 61,711 lifetime bounty points.
.... snip. ...
You have made contact with the child you are to rescue and you must get him back alive to Quin Telaren of Wehnimer's Landing.
A young human child arrives, following you.
--- Lich: step2 active.
```

**Comment by gs4onurb** [comment]
I'd say 25% of the time when I exit Maaghara Tower with a child, it starts going to Zul Logoth.
