### ISSUE TITLE
[rfc] Ebounty causing Bigshot to start rest routine when saturated

### ISSUE THREAD

**Issue by GilbertMartinez** [elanthia-online/scripts#1153]
### Script Name

ebounty.lic

### RFC

When the character is saturated and is waiting for the bounty timer to expire it triggers bigshot to run in between bounties. However, when bigshot begins it notices your saturated and then does the return routine which includes fogging and rest scripts/commands. This is different than the behavior of just running bigshot while saturated yourself as opposed to having ebounty trigger it.

### Context

It's causing additional spam to the rooms because you fog out and rerun a routine that didn't need to be run.

### Examples

- If player is Saturated and Bigshot is triggered then no actions should be sent to the game until its ready to hunt. As opposed to running the rest routine on start.

**Comment by Deysh** [comment]
Does this happen when you turn in a bounty or if you start ebounty and you are already saturated?

**Comment by GilbertMartinez** [comment]
> Does this happen when you turn in a bounty or if you start ebounty and you are already saturated?

This happens when ebounty is already running, recently turned in a bounty and it’s waiting for the next one. It then triggers bigshot to “hunt in between” the timer expiring. I can update this with logs once it happens again today.

**Comment by GilbertMartinez** [comment]
Adding log of incident.. I edited room information to keep that out.

`

 Not Hunting: Mana less than 90%
 Total Elapsed Time:  26 Minutes 1 Seconds

>
You feel the extra courage wane.
>
--- Lich: bigshot active.
>
 Bigshot resting: fried.
[bigshot]>stance defensive
You are now in a defensive stance.
>
[bigshot]>symbol of courage
You feel more courageous.
>
[ Symbol of Courage: +0:04:19, 0:08:39 remaining. ]
[bigshot]>incant 515
You carefully weave the Rapid Fire spell into the air, trails of indigo and silver mist following the somatic components.  Twisting and twining, the skeins of energy leech power from you and, as you unleash the spell, you feel droplets of moisture dripping from your fingertips...
Your spell is ready.
You gesture.
You feel the magic surge through you.
Cast Roundtime 0 Seconds.
(Forcing stance down to guarded)
>
[ Rapid Fire: +0:01:00, 0:00:59 remaining. ]
>
[bigshot]>incant 930
You carefully weave the Familiar Gate spell into the air, trails of indigo and silver mist following the somatic components.  Twisting and twining, the skeins of energy leech power from you and, as you unleash the spell, you feel droplets of moisture dripping from your fingertips...
Your spell is ready.
You gesture.
Pale, swirling mist begins to billow out from nothingness before you, and quickly coalesces into a small orb of shifting essence.  Suddenly, the orb expands and forms an elliptical portal of swirling blues and blacks, its edges shrouded in dancing blue-white mist.
Cast Roundtime 1 Second.
>
[bigshot]>go portal
You step through the shifting portal.
[Inside Town] 

[bigshot]>stance defensive
You are now in a defensive stance.
>
[bigshot]>store weapon
You aren't holding any weapons in your hands.
>
--- Lich: eherbs active.

 Missing herb for Hypochondriasis.

--- Lich: eherbs has exited.
--- Lich: eloot active.
>
--- Lich: eloot has exited.
--- Lich: go2 active.
[go2: input: restinglocation]`

**Comment by Deysh** [comment]
Thanks that helps, let me see if I can unmangle that.

**Comment by Deysh** [comment]
Not really seeing anything that jumps out at me. Couple things that could help
Can you confirm your current version please: ;version ebounty
Does this happen every time or just occasionally?
Can you attached the output of ;ebounty test

**Comment by GilbertMartinez** [comment]
It happens every single time when its in between bounties. You can ping me at Drinknation#6628 and I can provide you live feedback if you need it.

>;version ebounty
--- Lich: version active.
```
Installed script versions: ebounty==1.1.16
```
--- Lich: version has exited.
--- Lich: ebounty active.
[ebounty:  Ebounty Version: 1.1.16]
[ebounty: ]
[ebounty: --------------- Settings ---------------]
[ebounty: [:bounty_types, ["boss_culling", "culling", "heirloom_loot", "skinning", "rescue", "foraging"]]]
[ebounty: [:selling_script, ""]]
[ebounty: [:default_profile, "nelemar-latest-2"]]
[ebounty: [:escort_types, []]]
[ebounty: [:forage_options, ["use_506", "use_919", "run"]]]
[ebounty: [:creature_exclude, ["greater water elemental", "water elemental", "dissembler", "triton executioner", "ethereal triton sentry", "triton magus"]]]
[ebounty: [:culling_max, 28]]
[ebounty: [:gem_max, 30]]
[ebounty: [:herb_max, 30]]
[ebounty: [:skin_max, 30]]
[ebounty: [:extra_skin, 4]]
[ebounty: [:exp_pause, false]]
[ebounty: [:only_required_creatures, true]]
[ebounty: [:use_boosts, true]]
[ebounty: [:use_vouchers, true]]
[ebounty: [:once_and_done, false]]
[ebounty: [:rest_random, false]]
[ebounty: [:basic, false]]
[ebounty: [:resting_room, "28709"]]
[ebounty: [:healing_script, ""]]
[ebounty: [:default_name, "nelemar-latest-2"]]
[ebounty: [:profile_name_bandits, "nelemar-latest-2"]]
[ebounty: [:bandits_profile, "nelemar-latest-2"]]
[ebounty: [:kill_bandits, false]]
[ebounty: [:names_a, "triton executioner"]]
[ebounty: [:profile_a, "nelemar-latest-2"]]
[ebounty: [:profile_name_a, "nelemar-latest-2"]]
[ebounty: [:kill_a, false]]
[ebounty: [:names_b, "triton radical"]]
[ebounty: [:profile_b, "nelemar-latest-2"]]
[ebounty: [:profile_name_b, "nelemar-latest-2"]]
[ebounty: [:kill_b, true]]
[ebounty: [:names_c, "siren"]]
[ebounty: [:profile_c, "nelemar-latest-2"]]
[ebounty: [:profile_name_c, "nelemar-latest-2"]]
[ebounty: [:kill_c, true]]
[ebounty: [:names_d, "triton combatant"]]
[ebounty: [:profile_d, "nelemar-latest-2"]]
[ebounty: [:profile_name_d, "nelemar-latest-2"]]
[ebounty: [:kill_d, true]]
[ebounty: [:names_e, "spectral triton defender"]]
[ebounty: [:profile_e, "nelemar-latest-2"]]
[ebounty: [:profile_name_e, "nelemar-latest-2"]]
[ebounty: [:kill_e, true]]
[ebounty: [:names_f, "ethereal triton sentry"]]
[ebounty: [:profile_f, "nelemar-second-floor"]]
[ebounty: [:profile_name_f, "nelemar-second-floor"]]
[ebounty: [:kill_f, false]]
[ebounty: [:names_g, "triton magus"]]
[ebounty: [:profile_g, "nelemar-second-floor"]]
[ebounty: [:profile_name_g, "nelemar-second-floor"]]
[ebounty: [:kill_g, false]]
[ebounty: [:names_h, ""]]
[ebounty: [:profile_h, ""]]
[ebounty: [:profile_name_h, ""]]
[ebounty: [:kill_h, false]]
[ebounty: [:names_i, ""]]
[ebounty: [:profile_i, ""]]
[ebounty: [:profile_name_i, ""]]
[ebounty: [:kill_i, false]]
[ebounty: [:names_j, ""]]
[ebounty: [:profile_j, ""]]
[ebounty: [:profile_name_j, ""]]
[ebounty: [:kill_j, false]]
[ebounty: [:silence, true]]
[ebounty: [:debug, false]]
[ebounty: [:heirloom_options, ["run", "use_506", "use_919", "use_402"]]]
[ebounty: [:forage_prep_commands, "gird"]]
[ebounty: [:forage_prep_scripts, ""]]
[ebounty: [:forage_post_commands, "sheath"]]
[ebounty: [:forage_post_scripts, ""]]
[ebounty: [:heirloom_prep_commands, ""]]
[ebounty: [:heirloom_prep_scripts, ""]]
[ebounty: [:heirloom_post_commands, ""]]
[ebounty: [:heirloom_post_scripts, ""]]
[ebounty: [:location1, "Whistler's Pass"]]
[ebounty: [:location2, "Widowmaker's Road"]]
[ebounty: [:location3, "Old Logging Road"]]
[ebounty: [:location4, ""]]
[ebounty: [:location5, ""]]
[ebounty: [:location6, ""]]
[ebounty: [:location7, ""]]
[ebounty: [:location8, ""]]
[ebounty: [:location9, ""]]
[ebounty: [:location10, ""]]
[ebounty: [:location11, ""]]
[ebounty: [:location12, ""]]
[ebounty: [:bad_room1, "37,38,39,40,41"]]
[ebounty: [:bad_room2, "30609,30610,30611,30613,30614,30615,30616,30617,30618,30619,30811,30817,28918,28919,28920,28921,28922,28923,28929,28930,28931,28932,28978,29078,29079,29081,29089"]]
[ebounty: [:bad_room3, "12532,12533,14729"]]
[ebounty: [:bad_room4, ""]]
[ebounty: [:bad_room5, ""]]
[ebounty: [:bad_room6, ""]]
[ebounty: [:bad_room7, ""]]
[ebounty: [:bad_room8, ""]]
[ebounty: [:bad_room9, ""]]
[ebounty: [:bad_room10, ""]]
[ebounty: [:bad_room11, ""]]
[ebounty: [:bad_room12, ""]]
[ebounty: [:escort_prep_commands, ""]]
[ebounty: [:escort_prep_scripts, ""]]
[ebounty: [:escort_post_commands, ""]]
[ebounty: [:escort_post_scripts, ""]]
[ebounty: [:herb_exclude, []]]
[ebounty: [:keep_hunting, false]]
[ebounty: ----------------------------------------]
[ebounty: ]
--- Lich: ebounty has exited.
>

**Comment by Deysh** [comment]
Identified to be a comparison issue during the should_hunt? method. Will update in next bug fix but found a work around for the time being to set should_rest to 99 instead of 100
