### ISSUE TITLE
[eherbs] setup not saving Sigil of Mending

### ISSUE THREAD

**Issue by 3ternalhunter** [elanthia-online/scripts#1187]
### Script Name

eherbs.lic

### Bug Report

When checking off "Use Sigil of Mending" from the setup screen, when Close is selected the setting is not saved.
If you open setup a second time the option is unchecked.
My character knows how to use Sigil of Mending.

### Expected Behavior

Sigil of Mending should remain checked after the setup is closed, with the setting being saved and used in game.

### Current Behavior

The checkbox for Sigil of Mending unchecks itself when "Close" is selected. The setting either reverts or is not saved.

**Comment by Deysh** [comment]
Thanks for the bug report. This will be fixed on the next release (v1.6.0) I'll close out this item once it does. There is an active PR if you want to grab a copy.
