### ISSUE TITLE
Missing Aggressive NPC for centaur

### ISSUE THREAD

**Issue by ADarkElf** [elanthia-online/scripts#125]
## 🤔 Expected Behavior

**target = GameObj.npcs.find { |npc| npc.type =~ /aggressive npc/** does not recognize "bay centaurs" as aggressive.

## 😯 Current Behavior

Will not attack centaurs with the "bay" adjective.

## 💁 Possible Solution

Add "bay" variable to **(?:white |black |tan |roan )?centaur**

## 🔦 Context

Script will not attack "bay centaurs".

**Comment by ondreian** [comment]
Thanks, will be fixed in the next deploy hopefully
