### ISSUE TITLE
[gameobj] More Additions for Aggressive NPCs

### ISSUE THREAD

**Issue by ADarkElf** [elanthia-online/scripts#127]
## 🤔 Expected Behavior
**target = GameObj.npcs.find { |npc| npc.type =~ /aggressive npc/** should target and attack the npcs listed below.

## 😯 Current Behavior

Any script using **target = GameObj.npcs.find { |npc| npc.type =~ /aggressive npc/** will not attack the npcs listed below.

## 💁 Possible Solution

Add the following entries to <type name="aggressive npc">
(?:glittering|scintillating) zombie
(?:black|mangy|spotted|mongrel) wild dog
brindle wild hound
mongrel wolfhound

**Comment by ondreian** [comment]
the new miniboss modifiers have their own issue (#89)
Where are the dog creatures from?

**Comment by ADarkElf** [comment]
The dogs are from the Yegharren Plains near Ta’Illistim.  There are a couple of types that spawn besides the mongrel wolfhound.

**Comment by ondreian** [comment]
Thanks, I just wanted to go and see about skins & such to make sure they
are properly recorded.

**Comment by mrhoribu** [comment]
Fixed and resolved via #1225 and the boon update to GameObj. Closing.
