### ISSUE TITLE
a heart of smooth black glaes

### ISSUE THREAD

**Issue by gs4-ashraam** [elanthia-online/scripts#133]

**Comment by sandersch** [comment]
I didn't think they would be, but turns out these can be purified:

```
You weave another verse into your harmony, directing the sound of your voice at a heart of smooth black glaes.
In response to your voice, the smooth black glaes glows luminously, its crystalline structure reforming as the gem becomes more perfect.
When the song ends, you notice the smooth black glaes sparkles a little more and is void of some natural imperfections. 
```

**Comment by ondreian** [comment]
Do these still try to kill you/curse when you loot the skayls?

**Comment by sandersch** [comment]
Arianiss and Ashraam said they don't come out cursed and hot any more.

**Comment by ondreian** [comment]
Seems gem like to me then, as long as this update doesn't kill people

**Comment by sandersch** [comment]
Hunting some of these to generate more test items. They can also be "hollow smooth black glaes".

I think these should be excluded from the uncommon category as well.

**Comment by ondreian** [comment]
That makes sense to me that they are not `uncommon`
