### ISSUE TITLE
[script] ebounty not matching herbs correctly

### ISSUE THREAD

**Issue by bmg90001** [elanthia-online/scripts#1368]
### Script Name

ebounty - wrong forage name wild phlox

### Bug Report

ebounty forages for sprig of wild phlox, and the game is expecting wild phlox to be foraged. This might apply to all of the sprig of herbs.

### Expected Behavior

Shouldn't use sprig of, only wild phlox

### Current Behavior

searches for sprig of wild phlox which returns no herbs

### Possible Solution

?

**Comment by Deysh** [comment]
the look-up table for herbs isn't used. I left it there in case something like this came up.

For the last several versions ebounty uses the XML to determine the correct command to forage.
> forage_link = Regexp.last_match(1) if lines.any? { |l| l =~ /concoction that requires <d cmd=\"(.*?)\">/ }

It could be my regex match is off or the game is sending something strange. Are you able to capture the XML if you type bounty in game while having one of those tasks? You can use ;logxml

**Comment by bmg90001** [comment]
The herbalist in Ta'Vaalor, Maraene, is working on a concoction that requires <d cmd="forage sprig of jasmine">a sprig of jasmine</d> found in the Glaise Cnoc Cemetery near Ta'Vaalor.  These samples must be in pristine condition.  You have been tasked to retrieve 8 samples.
<prompt time="1701955171">&gt;</prompt>
<dialogData id='expr'><label id='yourLvl' value='Level 6' top='0' left='0' align='n' width='160' height='15'/><progressBar id='mindState' value='50' text='clear' top='45' left='3' align='n' width='160' height='15'/><progressBar id='nextLvlPB' value='53' text='7121 until next level' top='20' left='3' align='n' width='160' height='15'/></dialogData><prompt time="1701955201">&gt;</prompt>
<component id='room players'>Also here: <a exist="-11144768" noun="Eckius">Eckius</a></component>
<a exist="-11144768" noun="Eckius">Eckius</a> just arrived.
<prompt time="1701955220">&gt;</prompt>

**Comment by bmg90001** [comment]
[2023-12-07-07-18-05.txt](https://github.com/elanthia-online/scripts/files/13600654/2023-12-07-07-18-05.txt)

**Comment by Deysh** [comment]
Thanks. I'll look into it.

**Comment by Deysh** [comment]
not able to replicate the issue....

kneel
You kneel down.
K>forage sprig of jasmine
d100(Open): 7
You forage briefly and manage to find a sprig of jasmine!
Roundtime: 5 sec.

**Comment by bmg90001** [comment]
odd, I had to use jasmine to get it, same as the above two examples, (sprig of) wild lilac and (sprig of) wild phlox.

**Comment by bmg90001** [comment]
I even got the invalid noun error message "your not sure where it could be found" or whatever it says.

**Comment by Deysh** [comment]
if you get another one let me know, the awesome thing about intermittent bugs is they drive you crazy :)

**Comment by bmg90001** [comment]
Maybe it's zone specific. I was foraging around Ta'Vaalor. I'll let you know if it happens again.

**Comment by bmg90001** [comment]
[2023-12-07-09-45-29.txt](https://github.com/elanthia-online/scripts/files/13602138/2023-12-07-09-45-29.txt)
lich room ID 5834

**Comment by Deysh** [comment]
Did you have an active bounty requesting that herb? The reason I ask is that if you do and the link that is part of the bounty request is wrong then its a game bug.

**Comment by bmg90001** [comment]
I did for the first forage attempt, but not for the example a few minutes ago.
but you foraged successfully for sprig of jasmine and I could not.

**Comment by bmg90001** [comment]
Actually sprig of jasmine might be a bad example, I was able to forage that one using "sprig of jasmine"

**Comment by bmg90001** [comment]
but both of the first two examples had "sprig of" in the link on the quest panel

**Comment by bmg90001** [comment]
[ebounty]>forage for dill
d100(Open): 72
You forage briefly and manage to find a sprig of dill!
Roundtime: 5 sec.

This one looks to be handled correctly, even though the underlined part of the bounty page is sprig of dill

**Comment by Deysh** [comment]
Closing. Please reopen an issue if this happens again.
