### ISSUE TITLE
[script] Bigshot Looping Voln Symbol Cast when out of Favor

### ISSUE THREAD

**Issue by gsiv-Vailan** [elanthia-online/scripts#1393]
### Script Name

bigshot.lic

### Bug Report

If you run out of favor while using bigshot and have voln abilities configured to use for hunting like symbol of supremacy and it tries to refresh it when it expires it will go into a repeated loop of trying to use that symbol. I didnt test to see if it would still respond to things like fleeing but i was in a room with about 6 mobs and it just kept trying to do symbol of supremecy over and over for over a minute before i stopped it and removed my symbols from bigshot while i had no favor. 

### Expected Behavior

I would have expected it to wait to use the symbol until there was enough favor like spells do with mana or CMANs do with Stamina.

### Current Behavior

it just repeatedly cycles trying to use the symbol over and over and over and stops doing any of the other functions like wandering or combat even with mobs in the same room.

### Possible Solution

Now that favor is more easily retrievable it should use that favor as a check to see if the symbol is usable and if not skip/delay its use until it.

**Comment by Deysh** [comment]
A toggle is being added on the Hunting tab as part of version 5.3.0 to check for favor before trying to cast.
