### ISSUE TITLE
sidewinder scale missing from gameobj-data.xml

### ISSUE THREAD

**Issue by mrhoribu** [elanthia-online/scripts#146]
## 🤔 Expected Behavior
Expect "a sidewinder scale" to be recognized as a skin and sellable to the furrier.

## 😯 Current Behavior
Not recognized as any TYPE data currently.

## 💁 Possible Solution
Add to both SKIN and FURRIER type data.

**Comment by sandersch** [comment]
:+1: sounds good to me. Probably should be added to https://github.com/elanthia-online/scripts/blob/master/type_data/migrations/7_sos.rb
