### ISSUE TITLE
brown boar hides

### ISSUE THREAD

**Issue by pflats** [elanthia-online/scripts#161]
## 🤔 Expected Behavior

`brown boar hide`s should be classified as `skin`s

## 😯 Current Behavior

`brown boar hide`s are not classified as `skin`s

## 💁 Possible Solution

make `brown boar hides skin`s. perhaps remove `brown boar skin`s as `skin`s in the process, as they do not exist. (the wiki had the wrong skin listed for brown boars. i updated it.)

## 🔦 Context

some loot scripts leave `brown board hide`s on the ground.

## 💻 Examples

```
other (13): a brown boar hide (9), [...]
skin (37): a bear hide (15), a black boar hide (6), [...]
```

**Comment by sandersch** [comment]
Thanks for submitting this issue. I just merged the fix so gameobj-data.xml should be updated in the repo in a few minutes.
