### ISSUE TITLE
Agresh is a proper noun (Agresh bear claws)

### ISSUE THREAD

**Issue by pflats** [elanthia-online/scripts#165]
## 🤔 Expected Behavior

Agresh bears' skins should be Agresh bear claws

## 😯 Current Behavior

Agresh bears' skins are agresh bear claws

## 💁 Possible Solution

Capitalize the A in Agresh.

## 🔦 Context

This issue has affected me because Agresh bear claws are not recognized as skins, so scripts do not interact with them. Meanwhile, agresh bear claws are recognized as skins, but do not exist. I am uncertain how I feel about things that do not exist being recognized.

**Comment by athias** [comment]
Corrected in Pull Request #168

**Comment by athias** [comment]
Commit for this was approved, this issue can be closed.

**Comment by mrhoribu** [comment]
see comments
