### ISSUE TITLE
rofl-puzzles.lic -> drop candle

### ISSUE THREAD

**Issue by rsecor** [elanthia-online/scripts#229]
| Software         | Info       |
| ---------------- | ---------- |
| ruby version     | x
| script           | rofl-puzzles.lic

# 🐛 bug report

## 😯 Current Behavior

>drop candle
You notice that the beeswax pillar candle is marked as unsellable and stop yourself.
[You can disable this feature by using the SET NOMARKEDDROP OFF command at any time.]

>drop candle
You drop the beeswax pillar candle.
## 💁 Possible Solution
If "You notice that the beeswax pillar candle is marked as unsellable and stop yourself."
Then send "SET NOMARKEDDROP OFF"
send "drop candle"
send "SET NOMARKDROP ON"

## 🔦 Context

Puzzle failure.

**Comment by rsecor** [comment]
Need to verify if the candle itself is set as marked not to drop by the server-side by default.

**Comment by rsecor** [comment]
The current guess is that all candles made by players in GemStone are set to be marked by default.
When a player has their settings setup to not drop a marked item then they will not drop it.
This means getting this changed will be a hassle since it affects all candles made by players, not just this single candle.
I currently believe the best bet is to script around this as explained in the possible solution.

**Comment by sandersch** [comment]
I had some more runs and was lucky enough to get this twice in a short period so was able to verify that it with NOMARKEDDROP on or off.
