### ISSUE TITLE
Bigshot can't handle Sanctuaries

### ISSUE THREAD

**Issue by goatface** [elanthia-online/scripts#25]
Hisskra shaman, and likely other creatures like minotaur magi, use a Sanctuary effect when they raise their fallen comrades.  Bigshot should think to change the room , but instead it keeps preparing and releasing an attack spell until all mana is drained.  Did not check results for swinger, but here is the line to catch for casters:

`Be at peace my child, there is no need for spells of war in here.`

**Comment by mrhoribu** [comment]
I quickly looked at ;bigshot to see if there would be an easy implementation to resolve this and there really isn't one that doesn't require re-writing all the custom cmds for bigshot to watch server_strings. As of now it doesn't really look at them so there is no way to have it check for that. I'm open to suggestions if you have any if you've done something yourself.

On my own personal ;bigshot hunting I have a monitor active script I use that watches for that line specifically (and others). When it sees that line, it will ;pause bigshot and run to a safe room I designated in my hunting grounds, wait 1 second, check that all conditions are cleared (frenzy, silence, interference, etc), then ;unpauses bigshot and off it goes to hunting again.

**Comment by goatface** [comment]
No specific suggestion.  I kill it and restart it.

**Comment by ImperArx** [comment]
If you add the following to your `flee from environment message` section on the `Attacking` tab, it will move on when it sees the sanct or tries to cast in a sancted area.

`a sense of peace and calm settles over the area.|be at peace my child, there is no need to fight here.`

**Comment by mrhoribu** [comment]
Ability to resolve with existing flee from environment message box. No need for additional coding or supplemental scripts. Closing.
