### ISSUE TITLE
OSA Mobs

### ISSUE THREAD

**Issue by mrhoribu** [elanthia-online/scripts#288]
## 🤔 Expected Behavior

OSA Mobs should be seen as aggressive

## 😯 Current Behavior

They aren't seen at all

## 💁 Possible Solution

Add to aggressive and undead appropriately 

## 💻 Examples

battle-scarred hulking krolvin huntmaster
battle-scarred hulking krolvin warden
battle-scarred krolvin huntmaster
battle-scarred krolvin huntmistress
battle-scarred krolvin warden
dwarven pillager
dwarven pirate
dwarven raider
dwarven scout
dwarven waylayer
elven brigand
elven pillager
elven pirate
elven raider
elven robber
elven scout
elven waylayer
erithian pillager
erithian raider
ethereal brigand
ethereal pillager
ethereal pirate
ethereal raider
ethereal scout
ethereal waylayer
ghostly gnomish rogue
ghostly half-elven marauder
ghostly halfling rogue
ghostly human brigand
ghostly human marauder
ghostly human mugger
ghostly human outlaw
ghostly human rogue
ghostly human thief
giantman brigand
giantman marauder
giantman mugger
giantman pillager
giantman pirate
giantman raider
giantman robber
giantman scout
gnomish brigand
gnomish mugger
gnomish pillager
gnomish pirate
gnomish raider
gnomish rogue
gnomish scout
gnomish waylayer
grizzled krolvin champion
grizzled krolvin huntmistress
grizzled krolvin warden
grizzled krolvin warlord
half-elven brigand
half-elven marauder
half-elven mugger
half-elven pillager
half-elven pirate
half-elven raider
half-elven scout
half-elven thug
half-elven waylayer
half-krolvin brigand
half-krolvin pirate
half-krolvin waylayer
halfling brigand
halfling highwayman
halfling pillager
halfling pirate
halfling raider
halfling rogue
halfling scout
halfling thug
halfling waylayer
hulking krolvin archmage
hulking krolvin champion
hulking krolvin destroyer
hulking krolvin obliterator
hulking krolvin paragon
hulking krolvin templar
hulking krolvin tormentor
hulking krolvin triggerman
hulking krolvin warlord
human bandit
human brigand
human marauder
human mugger
human outlaw
human pillager
human pirate
human raider
human rogue
human scout
human thief
human waylayer
menacing krolvin archmage
menacing krolvin destroyer
menacing krolvin obliterator
menacing krolvin paragon
menacing krolvin templar
menacing krolvin triggerman
menacing krolvin warlord
seasoned hulking krolvin warden
seasoned krolvin warden
The Ethereal Captain
The Krolvin Captain
The Pirate Captain
towering krolvin archmage
towering krolvin destroyer
towering krolvin obliterator
towering krolvin paragon
towering krolvin scout
towering krolvin templar
towering krolvin tormentor
towering krolvin triggerman
towering krolvin warlord
unworldly brigand
unworldly pillager
unworldly pirate
unworldly raider
unworldly scout
unworldly waylayer
weathered hulking krolvin warden
weathered krolvin huntmistress
weathered krolvin warden

**Comment by ondreian** [comment]
I agree that if we want to keep maintaining the `aggressive` tag we should add these, but `GameObj.targets` is **always** better

**Comment by mrhoribu** [comment]
It's always better for sure. I have a script I have someone running doing OSA and just added an `aggressive` sanity check to only capture NPC names that aren't already cataloged. So I'll post that list tomorrow.

**Comment by mrhoribu** [comment]
Part of the issue with GameObj.targets is it still has some odd things like 709 arms and storyline NPCs and some other oddities.

**Comment by ondreian** [comment]
For me, I think the most important thing to do is ensure all `undead` targets have the appropriate tag (for all the special logic they require)

**Comment by mrhoribu** [comment]
closed due to #290 resolving issue.
