### ISSUE TITLE
Puritan Expanded Statistics Capture

### ISSUE THREAD

**Issue by LordWhirlin** [elanthia-online/scripts#299]
# 💬 RFC

I'm looking to have additional statistics tracked on Puritan.  Specifically, I am looking for the total number of purification attempts that were conducted.  I would like the information presented in a three column format based on the three potential outcomes (Purification threshold reached, Orb'ed, or Exploded), with the rows being the # of purification rounds, and the cells being the quantity of gems that fell into these conditions:  

Example:

Purification completed:  Statistics:
Attempts |  Orbed | Threshold Reached | Exploded
1 | 2 | 1 | 0
2 | 1 | 0 | 0
3 | 2 | 0 | 0

**Comment by ondreian** [comment]
I'm not going to change the format to a table, it's meant to be a quickly parse-able sitrep, but I have added round statistics and shatter statistics.  You can tell how many you orbed by measuring the orb sack before and after if necessary.
