### ISSUE TITLE
jinx: spell-list.xml checks on update

### ISSUE THREAD

**Issue by mrhoribu** [elanthia-online/scripts#380]
spell-list.xml when downloaded via jinx should check if it's currently set to be updatable via ;repository download-updates and if so, remove it from the list. Also, upon successful update, automatically do a `Spell.load` to not have to relog to load spells into current session.

Code block that was shared to possibly read settings from `;repository` to know whether spell-list.xml is in it's Settings for being updatable.

```ruby
Marshal.load(Lich.db.get_first_value('SELECT hash FROM script_auto_settings WHERE script=? AND scope=?;',
                                     'infomon'.encode('UTF-8'), 
                                     "#{XMLData.game}:#{the_char.capitalize}".encode('UTF-8')))
```

**Comment by mrhoribu** [comment]
```ruby
repo_settings = Marshal.load(Lich.db.get_first_value('SELECT hash FROM script_auto_settings WHERE script=? AND scope=?;', 
  'repository'.encode('UTF-8'), 
  ":".encode('UTF-8')))

repo_spell_list = repo_settings['updatable'][:scripts].find { |script| script[:filename] == "spell-list.xml"}
echo repo_spell_list.inspect
```

Above should return nil if not found, true if it is. Should be able to then issue a `Script.run("repository", "unset-updatable spell-list.xml")` command as not sure how easy it would be to directly modify the Lich.db3 otherwise.

**Comment by ondreian** [comment]
Should just be a simple `UPDATE` SQL statement with the re-marshalled hash
