### ISSUE TITLE
gameobj-data.xml & vaalin-rimmed glass bottle

### ISSUE THREAD

**Issue by gs4-Xanlin** [elanthia-online/scripts#40]
I'm sure there's a reason that `/^glass bottle$/` is excluded from the `jar` type, but it seems to be causing an issue with the off-the-shelf alchemist bottles available in Ta'Illistim. Empty vaalin-rimmed glass bottles seem to be fine, only when they contain something do they fail to be typed correctly. 
```

You remove a vaalin-rimmed <a exist="144910325" noun="bottle">glass bottle</a> containing essences of earth from in your <a exist="144803946" noun="bag">courier bag</a>.

;e GameObj.inv.each{|i| i.contents.each {|o| echo "#{o.type}: #{o.inspect}" if o.noun =~ /bottle/  } }

[exec1: jar: #<Games::Gemstone::GameObj:0xc9167b8 @id="144803984", @noun="bottle", @name="black sea glass bottle", @before_name="an antiqued", @after_name="containing uncut emeralds">]
[exec1: jar: #<Games::Gemstone::GameObj:0xc92ef80 @id="144803983", @noun="bottle", @name="white sea glass bottle", @before_name="a translucent", @after_name="containing uncut diamonds">]
[exec1: : #<Games::Gemstone::GameObj:0x10e415e0 @id="144910325", @noun="bottle", @name="glass bottle", @before_name="a vaalin-rimmed", @after_name="containing essences of earth">]

You remove a vaalin-rimmed <a exist="144910325" noun="bottle">glass bottle</a> containing essences of earth from in your <a exist="144803946" noun="bag">courier bag</a>.

<c>l in my hip
In the <a exist="144804018" noun="hip-satchel">shadowy black hip-satchel</a> you see a <a exist="144910325" noun="bottle">vaalin-rimmed glass bottle</a>, 
```

**Comment by ondreian** [comment]
This a non-trivial issue and may require gm intervention to fix since the vaalin version is wrongly defined in the game.

`glass bottle` is also from the spitfire "message in the bottle" script and many of them still exist.

**Comment by ondreian** [comment]
According to the lovely Estild this has been fixed serverside, but you have to empty the jar and refill it for the new changes to take effect.

If it turns out there is actually still a GameObj issue, just reopen this, please.
