### ISSUE TITLE
Proposed change ot gameobj-data.xml:  Move ant larva from 'aggressive npc' to 'skin' name

### ISSUE THREAD

**Issue by OSXLich-Doug** [elanthia-online/scripts#41]
Ant larva listed as 'aggressive npc' type in gameobj-data.xml.

Propose moving ant larva to 'skin' name type in gameobj-data.xml.

Justification:  The game does not link ant larva (find from level 2 giant ant) in game with any tag.  Ant larva average 40 silver at furrier shops.

**Comment by sandersch** [comment]
It looks like giant ants have "ant pincher" as skins. Are the ant larva loot drops that sell at the furrier like scintillating fishscales and ambergris?

**Comment by OSXLich-Doug** [comment]
Yes.

Doug

**Comment by sandersch** [comment]
I sent a guy a there and was able to verify this myself too. I also checked my logs and saw that the fire ants outside Ta'Vaalor also drop them. Created #42 to address.

**Comment by OSXLich-Doug** [comment]
Thank you, sir!

**Comment by sandersch** [comment]
Merged #42 and update pushed to the repo. These should be handled correctly now.
