### ISSUE TITLE
[poolparty.lic] doesn't like plates

### ISSUE THREAD

**Issue by Rencelas** [elanthia-online/scripts#446]
| Software         | Info       |
| ---------------- | ---------- |
| ruby version     |
| script           |

# 🐛 bug report

Poolparty.lic hangs up with junk plates are in boxes. They're "scripted or otherwise" and don't fall out automatically, so it pauses.

## 🤔 Expected Behavior

Should automatically remove or dump corroded plates and the like.

**Comment by Deysh** [comment]
Poolparty no longer supported
