### ISSUE TITLE
familiar.lic - catch additional `interference`

### ISSUE THREAD

**Issue by gs4-Xanlin** [elanthia-online/scripts#53]
To move out to recast when it's not a fizzle, but other interference:

if cast_result =~ /fizzle|Something in the area seems to interfere with the magic/

**Comment by mrhoribu** [comment]
This looks good and should work fine. Feel free to do a pull request to edit the code. Or let me know if you don't want to.

**Comment by sandersch** [comment]
Recommend making this an option so that you don't get a ton of complaints when this moves someone out of a merchant room or something.

**Comment by mrhoribu** [comment]
should be fixed with #54 being merged now.
