### ISSUE TITLE
Red Forest skins

### ISSUE THREAD

**Issue by ondreian** [elanthia-online/scripts#56]
GameObj doesn't have the skins from Red Forest defined.

**Comment by sandersch** [comment]
I think this is the full list of skins in that area based on the wiki entries:

direbear fang
heavy grey tusk
red eye
mossy beard
blood-stained bark
pure white feather

Can anyone else confirm?

**Comment by ondreian** [comment]
yeah these are what I found, with the exception of the direbear fang, I didn't kill any of those.

**Comment by sandersch** [comment]
Created #69 with test cases for each of these.
