### ISSUE TITLE
Jewelry nouns

### ISSUE THREAD

**Issue by Vyrshkana** [elanthia-online/scripts#58]
Here's my list of jewelry nouns (and source items).

bracelets	-	a trio of silver bracelets
wristcuff	-	a hammered copper wristcuff
choker	-	a choker of filament-caught pearl and hematite teardrops
bangle	-	a polished zebrawood bangle
wristlet	-	a shimmering sardonyx wristlet
signet	-	a polished mahogany thumb signet
waistchain	-	a sapphire-set rough silver waistchain
vambrace	-	a scuffed eonake vambrace etched with a two-headed serpent upon the underside
cuff	-	an elongated leather wrist cuff side-laced with sorrel twine
bangles	-	a set of cedar bangles gathered with a loop of grape vines
handflower	-	an oval-linked silver handflower beaded with tiny uncut aquamarines
hip-chains	-	
girdle	-	a triple-link blue imflass girdle
arm-cuff	-	a coiled copper oak leaf arm-cuff
basrenne	-	a silver-gilded rivergrass basrenne
armbands	-	a pair of thick spiral armbands of twisted copper and bronze
cufflinks	-	some silver and emerald cufflinks
hair-ornament	-	a sparkling citrine hair-ornament
wrist-cuff	-	a petite hammered copper wrist-cuff
earcuffs	-	some molded copper earcuffs draped with tiny bronze rings
ankle-chain	-	a coin-edged copper ankle-chain
neck-chain	-	a shimmering milky quartz neck-chain
signet-ring	-	a gold-streaked mica signet-ring
toe-ring	-	a glimmering rosespar toe-ring
waist-chain	-	a silver-traced white pearl waist-chain
hair-tie	-	a simple leather hair-tie
rings	-	a trio of jade and malachite-leafed rings
wristcuffs	-	a pair of gold-runed bronze wristcuffs
wrist-cuffs	-	a pair of dented steel wrist-cuffs
armlet - a coiled gold armlet dangling teardrop pearls
huiteo - an unbleached cotton huiteo
elothrai	-	a gold-linked blood agate elothrai
cincture	-	a platinum chain-linked cincture spaced with tiny jet stones
hair-ornaments	-	a pair of round pure silver hair-ornaments
browband	-	a thin gold browband studded with egg-shaped brightly shining green glimaerstones
ankle-chains	-	a series of golden ankle-chains beaded with red agate
necklet	-	a lacquered linden necklet with inward curling ends 
wristbands	-	a set of dark leather wristbands burned with stylized flames
footflower	-	a triple-linked bronze footflower decorated with modwir beads
hip-chain	-	a lapis and silver charm hip-chain affixed with tiny bells
wristchain	-	a thin-linked gold wristchain with rosebud-shaped bells 
geldaralad	-	a beaded and twisted vaalin geldaralad
earbobs	-	a pair of crimson blazestar earbobs
anklets	-	a pair of mithglin bell-strung anklets
ferroniere	-	a lapis-strung mithglin ferroniere bestrewn with opaline beads
coronet	-	a blackened silver coronet of overlapping scales
carcanet	-	a golden carcanet formed into interlocking palms
lavaliere	-	a smooth dark glass moon lavaliere
wristband	-	a tarnished silver wristband etched with a sleek feline
ankle-cuff	-	a belled silver mesh ankle-cuff
anadem	-	a burnished mithril anadem set with turquoise cabochons
chaplet	-	a simple copper chaplet dangling an oval-cut emerald
headpiece	-	a beribboned forget-me-not headpiece
periapt	-	an emerald trident periapt suspended from a grey leather thong
seer-stone	-	a tri-chained golden seer-stone
diadem	-	a carved polished ivory diadem
wristlets	-	some rose-embroidered ivory satin wristlets
handflowers	-	some delicate pewter and purple opal handflowers with bells
pectoral	-	a heavy gold pectoral
toe-rings	-	a set of ten gold toe-rings chain linked to birch anklets
hip-chain	-	a thick-linked golden hip-chain
chatelaine	-	a delicate gold chain-linked chatelaine
monocle	-	a red-tinted monocle suspended on a mithril chain
glasses	-	a pair of imflass-framed glasses
spectacles	-	some round gold-framed spectacles
necklaces	-	a trio of red-tinged purple sapphire rope necklaces
cloakpin	-	a kiln-shaped faceted emerald cloakpin 
wrist-spiral	-	a delicate rose gold wrist-spiral
hairband	-	a pink and white satin hairband
armcuff	-	a narrow beaten copper armcuff
manacles	-	a pair of discolored iron manacles
combs	-	some fine silver combs shaped into soaring falcons
hairclip	-	a glass-encased magpie feather hairclip
mitre	-	a bejeweled white cross-gilt mitre
thumb-ring	-	a solid square-jeweled thumb-ring decorated with falcons
barrettes	-	some sparkly red cherry barrettes 
hair-blossoms	-	some glimmering soft-hued hair-blossoms
belt-lamp	-	a pierced copper belt-lamp fitted with a short chain
belt-lantern	-	a filigreed vaalin belt-lantern fitted with a short chain
earbob	-	a silver-caged black pearl earbob
fibula	-	an amber-eyed silvery vultite lion’s head fibula
hairjewel	-	a black opal hairjewel trailing two golden peacock feathers
garland	-	a yellow orange blossom garland
armcuffs	-	a pair of hammered copper armcuffs draped with crimson silk sleeves
hand-flower	-	a veniom-beaded snowflake hand-flower 
hoops	-	a pair of dark maoral hoops
studs	-	some platinum-edged scintillating diamond studs
hair-wreath	-	a pure white snow rose and crimson flamestalk hair-wreath

**Comment by ondreian** [comment]
I think we want to keep this limited to treasure drops, not all possible words/alters.

There are performance, precedence, and maintainability issues.
