### ISSUE TITLE
[gameobj] Add missing hide bundles

### ISSUE THREAD

**Issue by LeBigNasty** [elanthia-online/scripts#656]
## 💻 Examples

triton spines, claws, hides and firebird feathers are not present in gameobj

**Comment by mrhoribu** [comment]
We'll need examples of each of these things to try to properly go about testing and adding

NPC Gathered from: 
Unbundled full name: 
Bundled full name: 

Thanks.

**Comment by mrhoribu** [comment]
Looking through the existing gameobj-data.xml I see the following for individual usage of the four you gave. I can't find what `claw` you may be referring too so will need more info on that. Also need to get a sample of these and what they fully look like bundled.

- elongated triton spine (triton radical, nelemar)
- iridescent triton hide (triton magus, nelemar)
- soft red firebird feather (firebirds? wiki has it as just a red firebird feather, F'Eyrie)

Will need to get on Test instsance and go grab some of these and see what can be done.

**Comment by LeBigNasty** [comment]
bundle of triton spines
bundle of triton hides
bundle of red firebird feathers
bundle of gold-flecked claws

**Comment by mrhoribu** [comment]
Should now be resolved.
