### ISSUE TITLE
[child2.lic] Bug: goes to WL instead of SH for Varnuvar tasks from SH

### ISSUE THREAD

**Issue by LeBigNasty** [elanthia-online/scripts#657]
| Software         | Info       |
| ---------------- | ---------- |
| ruby version     |
| script           |

# 🐛 bug report

## 🤔 Expected Behavior

Return should go to Solhaven Gate Guard

## 😯 Current Behavior

Path takes you to WL gate guard

**Comment by mrhoribu** [comment]
Issue is with mapdb in timeto pathing for closest advguild tag. Changing the exit room coming out of castle Varunar to 15sec going to WL changes pathing for closest advguild (and other town tags) to prefer SH.
