### ISSUE TITLE
[jinx.lic] Prevent incorrect syntax for script/data for non .lic files

### ISSUE THREAD

**Issue by LeBigNasty** [elanthia-online/scripts#658]
| Software         | Info       |
| ---------------- | ---------- |
| ruby version     |
| script           |

# 🐛 bug report

Several users are using incorrect syntax for non .lic files like eloot.ui. They are defaulting to ;jinx script install eloot.ui vice ;jinx data install eloot.ui.

Request script install block non .lic with an error or merge functionality of data/script into one noun and provide proper handling based on file extension.

**Comment by mrhoribu** [comment]
Currently eloot.ui is classified as a `data` type per the manifest/jinxp. But it can be referenced via `;jinx script info eloot.ui`, `;jinx script install eloot.ui` or `;jinx script update eloot.ui`. Ignoring that it's a `data` type and instead gets pushed into the scripts folder. Would expect type `data` to only be put in the data folder and also rejected from being referenced via `;jinx script` and force usage of `;jinx data` instead.

**Comment by mrhoribu** [comment]
Should be corrected via #678
