### ISSUE TITLE
[login.lic] Change to elogin and update functionality

### ISSUE THREAD

**Issue by LeBigNasty** [elanthia-online/scripts#661]
# 💬 RFC

## 🔦 Context

Request name change to support repo transition. Also when we switched to Wrayth Athias and others expressed some needed security changes to ;login that would be welcome to add as well. I would defer to them to what security functions they expressed need for

**Comment by mrhoribu** [comment]
@athias Any context to what other updates LeBigNasty is referring too. I don't see an issue with changing the name so it can be put on the `;repo` as well.

**Comment by mrhoribu** [comment]
Spoke with Athias, Current version seems to correct outstanding issues that can be addressed easily. Should be safe to merge/close.
