### ISSUE TITLE
[bigshot] add RiftCrawler escape similar to roa'ter

### ISSUE THREAD

**Issue by LeBigNasty** [elanthia-online/scripts#695]
### Script Name

bigshot

### RFC

Add rift crawler escape to bigshot in the same manner that roa'ter escape is utilized. Both code segments should probably be cleaned up

**Comment by snperry85** [comment]
Cleaned up roa'ter escape. RiftCrawler and roa'ter bellies are identical. Works for both as is.

**Comment by mrhoribu** [comment]
Closed via #700
