### ISSUE TITLE
[bigshot.lic] Bard song quiet command check not complete 

### ISSUE THREAD

**Issue by OSXLich-Doug** [elanthia-online/scripts#699]
### Script Name

bigshot.lic

### Bug Report

Bigshot low level bards get annoying messages.  (issue with code starting line 4092).  Issue is that the silent check does not check for no songs, it presumes a song is going.  Leads to extra needless messaging and delays moving between rooms (command times out rather than completes).

[bigshot]>north
[Wehnimer's Sewer, Nexus - 3937]
Obvious exits: north, northeast, east, southeast, south, southwest, west, northwest
>
You are not singing any songs.
>
You are not singing any songs.
>
[bigshot]>northwest
[Abandoned Sewer - 3938]
Obvious exits: southeast, northwest

### Expected Behavior

Change quiet command check to include 'not singing any songs' as a viable end of check.

### Current Behavior

Already described

### Possible Solution

Already described

### Possible Solution

Already described

**Comment by snperry85** [comment]
PR submitted. Thanks Doug. Yes I expect bards to always be singing.

**Comment by OSXLich-Doug** [comment]
> PR submitted. Thanks Doug. Yes I expect bards to always be singing.

Thanks, and thanks for the rapid turn!
