### ISSUE TITLE
eforgery.lic - issue with material_oil

### ISSUE THREAD

**Issue by GSIV-Nidal** [elanthia-online/scripts#705]
### Script Name

eforgery

### Bug Report

Hi team. I don't actually have a character who can use eforgery, I am helping a friend by submitting this on their behalf (they weren't comfortable/couldn't figure out how to do it).  They are experiencing an error where eforgery is hitting an error and bombing out as part of the oil def.

### Expected Behavior

From what I can tell, this part of the script is checking for oil in the trough.

### Current Behavior

[eforgery]>stare my head-glyph
Your material is marked with a pattern, next you'll need to shape it somehow.
Glancing around you see a door to the forging chamber.
Roundtime: 5 sec.
>
[eforgery]>go door
[Rolton Forge - ] (u4907062)
A large, black iron anvil stands in the center of this chamber.  Within easy reach to either side of the anvil are a brick forge and a tempering trough.  Directly above the trough, suspended by a web of delicate, mithril chains, hangs a teardrop-cut crystal easily the size of a giantman.  One corner of the room is taken up by a cistern bearing the embossed brass image of a grazing rolton, and a leather bucket hangs from a hook on the wall next to it.  Heat from the brick forge fills the chamber.  Some discarded oilskins rest haphazardly in the corner.  You also see a red iron door.
Obvious exits: none
>
--- Lich: error: undefined local variable or method material_oil' for #<Object:0x159c0a38>
Did you mean?  material_no
               material_no=
               @material_no
               @material_noun
       eforgery:706:in oil'
       eforgery:621:in `tongs'
[eforgery]>look in trough

>
"In the trough you see a cork plug."
--- Lich: eforgery has exited.
![eforgery](https://user-images.githubusercontent.com/68789160/166437192-f330125a-27ed-4685-987f-4c31f732b339.jpg)

**Comment by mrhoribu** [comment]
This should be resolved with #706 . Closing.
