### ISSUE TITLE
[rfc] child2

### ISSUE THREAD

**Issue by LeBigNasty** [elanthia-online/scripts#718]
### Script Name

child2

### RFC

Child2 needs update to both handle child in Varnuvar castle to send to Vornavis and not to WL. 
Also new KF child bounties it bypasses the sentry at the gate and attempts to  head into docks area.

**Comment by mrhoribu** [comment]
There's already an existing open issue for this that can be added onto instead of creating an additional issue. See #657 and add comments there for additional requests. Closing this one.
