### ISSUE TITLE
SLOOT using noun instead of item ID in put_item

### ISSUE THREAD

**Issue by ajcapaldi** [elanthia-online/scripts#74]
Hi, I'm trying to use a two word noun (zirah bouk) as a skinning knife, so I'm having a problem with ;SLOOT where it gets the item correctly since it uses the object ID but it won't put it away properly b/c it calls it a "zirah bouk" and the game parses that incorrectly like it does with "lapis lazuli" (it needs to just say "zirah").  I believe this is an issue with sloot or it could be that "zirah" is not a GameObj, but I wasn't sure where else to post this to get help.  Thanks!

**Comment by ondreian** [comment]
I'm afraid that sloot lives outside of the `elanthia-online` scope for now and SpiffyJr has `slootbeta.lic` as a replacement.
