### ISSUE TITLE
[eherbs.lic] fix missing River's Rest R1 head wound

### ISSUE THREAD

**Issue by LeBigNasty** [elanthia-online/scripts#741]
### Script Name

eherbs

### Bug Report

River's Rest doesn't sell rose potion/minor head wound. Eherbs needs to be adjust to account for the lack of R1 head would potion from herbalist

  Catalog
  ----------------------------------------------------------------------
  1. some acantha leaf      10. some haphip root
  2. some wolifrew lichen   11. some basal moss
  3. some torban leaf       12. some pothinir grass
  4. some woth flower       13. some sovyn clove
  5. some ambrominas leaf   14. a bolmara potion
  6. some ephlox moss       15. a brostheras potion
  7. some cactacae spine    16. a talneo potion
  8. some calamia fruit     17. a wingstem potion
  9. some aloeas stem       18. a bur-clover potion

  Backroom Catalog
  ----------------------------------------------------------------------
  19. a tkaro root

**Comment by mrhoribu** [comment]
Seems more like a bug/issue with the RR herbalist that needs bug'd/brought to GM attention. I went ahead and BUG'd it ingame and also posted about it via the official Discord River's Rest channel. Likely just a very old overlook.
