### ISSUE TITLE
[Eloot.lic] mono formatting bleeding to other text

### ISSUE THREAD

**Issue by snperry85** [elanthia-online/scripts#876]
Eloots initial data gathering from stow list and ready list can bleed mono formatting to stray text that happens at the same time. Silent command needs to be updated to capture the `<output class="mono"/>`

https://github.com/elanthia-online/scripts/blob/3da6e83d0dffe7a1f6529c6ae6dd2806d5f9eb0f/scripts/eloot.lic#L420
`container_lines = ELoot.get_lines("stow list",/<output class="mono"\/>/)`

https://github.com/elanthia-online/scripts/blob/3da6e83d0dffe7a1f6529c6ae6dd2806d5f9eb0f/scripts/eloot.lic#L468
`ready_lines = ELoot.get_lines("ready list",/<output class="mono"\/>/)`

**Comment by mrhoribu** [comment]
Closed via #883
