### ISSUE TITLE
[rfc] Add 919 and 140 to Disarmed

### ISSUE THREAD

**Issue by LeBigNasty** [elanthia-online/scripts#943]
### Script Name

disarmed.lic

### RFC

In addition to recent improvements, request adding 140 and 919 before kneeling

**Comment by mrhoribu** [comment]
I like it, definitely pushing the options scope creep up. May be time to allow all these to be settings and perhaps add a gui option to go with it as well. As well as turn it into a module to be sure that things are namescoped properly.

Nice suggestion.

**Comment by LeBigNasty** [comment]
Perhaps @Deysh would like to take a crack at the UI and 140/919 elements.

**Comment by mrhoribu** [comment]
Resolved via ;ecleanse script release.
