### ISSUE TITLE
[gameobj] petrified sprite figurine

### ISSUE THREAD

**Issue by gs4lass** [elanthia-online/scripts#977]
### Brief Description

Please add petrified sprite figurine as valuable.

### Expected Behavior

Collected as a pawnshop item. It is a commonly dropped decorative item worth about 350 silvers. It comes from sprite family creatures on Mist Harbor. It is left differently than other loot. It is left almost as though it's what the become upon death

### Current Behavior

Currently, this item is not collected via the LOOT verb.

### Possible Solution

Add to the gameobj db as "valuable"

### Examples

>;e echo GameObj.loot
--- Lich: exec1 active.
[exec1: [#<Games::Gemstone::GameObj:0x169a3be0 @id="549243812", @noun="figurine", @name="petrified sprite figurine", @before_name=nil, @after_name=nil>]]
--- Lich: exec1 has exited.
>get figurine
You pick up a petrified sprite figurine.
>l figurine
Wrought from petrified banyan, the figurine is uncannily lifelike and looks to be frozen in a moment of terror.
>
You ask Cendadric to appraise a petrified sprite figurine.
Cendadric turns the figurine over in his hands a few times.
He smiles broadly and nods.  "Not a bad little find there.  I'll give you 350 for this if you'd like."

**Comment by mrhoribu** [comment]
Fixed via #995
